### ISSUE TITLE
demo.gif file is too big

### ISSUE THREAD

**Issue by stickylabdev** [jiyeonseo/spark-ar-left-right-game#1]

**Comment by jiyeonseo** [comment]
Thanks for the feedback! Let me update it as smaller one :)

**Comment by stickylabdev** [comment]
🥇

**Comment by jiyeonseo** [comment]
(update) https://github.com/jiyeonseo/spark-ar-left-right-game/blob/master/demo.gif 
it's ways cuter than before haha thanks :)

**Comment by stickylabdev** [comment]
:) 
,, thank you .. .:')
